apiVersion: v1
kind: Service
metadata:
  name: triton-detectron2
  labels:
    app: triton-detectron2
spec:
  selector:
    app: triton-detectron2
  ports:
    - name: http
      port: 8000
      targetPort: http
    - name: grpc
      port: 8001
      targetPort: grpc
    - name: metrics
      port: 8002
      targetPort: metrics
