apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: video-pipeline
data:
  LOG_LEVEL: INFO
  QUEUE_BACKEND: redis
  REDIS_STREAM_NAME: jobs
  REDIS_CONSUMER_GROUP: pipeline-workers
  TRITON_DETECTOR_URL: http://triton-detector:8000
  TRITON_CLASSIFIER_URL: http://triton-classifier:8000
  METRICS_PORT: "9090"
